uoftblueprint/centre-for-dreams

.github/workflows/cd.yml
Creates a cron every 2 hours that checks for new commits and deploys to Render if a new commit is found.
CI/CD is cool
Test in prod
=> Continuous deployment with Github Actions

apps/nextjs/src/pages/api/healthz.ts
Added a health check endpoint at `api/healthz`
Improving the stability of our deployment on Render.
Ran dev server and received 200 response on endpoint.
=> Create health check endpoint

README.md
Add RyanL123 to the list of contributors in README.md
Completes CFD-2
=> CFD-2: Add RyanL123 to contributors

README.md
Adding my github username (helenaglow) to the readme contributors! 🎉
Completes CFD-5
N/A
=> CFD-5 Add name to README - Helena

README.md
Adds my Github account to the contributors section in the readme file. 
Completes CFD-9
N/A
=> add: name to contributors

README.md
=> Add Minh to README.md

.env.example, turbo.json
Adds `DIRECT_URL` variable to `.env.example`
Prisma commands will not work if this variable is not specified.
=> Update .env.example with DIRECT_URL

README.md
Added my name to the contributors list on README.md.
CFD-6
=> Add Ram to contributors

apps/nextjs/src/pages/api/healthz.ts
Deleted unused health check file
File is no longer being used
=> deleted health check

apps/nextjs/src/utils/api.ts
Invalidates all queries when mutation is performed so that developers do not need to manually invalidate context. Also removes SSR because I don't want to debug that.
Setup for dev starter tasks
=> Invalidate query cache on Mutation

apps/nextjs/src/pages/api/healthz.ts
=> Starter task setup

apps/nextjs/src/components/developers/ryanli.tsx, apps/nextjs/src/pages/index.tsx, packages/api/src/root.ts, packages/api/src/router/developer.ts
Adds the Ryan Li component that queries for some information about me. Also has an upvote field and button to read/write from and to the upvote field with Prisma.
Completes CFD-10
Manual testing was performed and it works (source: trust me)
=> CFD-10: Complete starter task 2 for Ryan Li 

apps/nextjs/src/components/developers/sarinali.tsx, apps/nextjs/src/pages/index.tsx, packages/api/src/router/developer.ts
Created a sarina component, added endpoint to router, added functionality to database to increase number of upvotes
CFD-16
=> Finished CFD-16

apps/nextjs/src/components/developers/jasonwang.tsx, apps/nextjs/src/pages/index.tsx, packages/api/src/router/developer.ts
Adds endpoints returning information about myself and to my increment the upvote counter. Also adds a card to the web app to display the information with a button to increment upvotes.
Completes CFD-13
Works after manual testing
=> Add: completed starter task 2

packages/db/prisma/migrations/20231019002903_add_posts_model/migration.sql, packages/db/prisma/schema.prisma
This PR adds the `Posts` model to Prisma with the specified fields
Completes CFD-20
Made example rows through Prisma Studio:
=> Add: posts model

apps/nextjs/package.json, apps/nextjs/src/pages/api/panel.ts, packages/api/package.json, packages/api/src/router/developer.ts, packages/api/src/trpc.ts, pnpm-lock.yaml
Added this package: https://github.com/iway1/trpc-panel to allow easy viewing, documentation, and execution of trpc endpoints
Devs can access the panel by going to localhost:3000/api/panel
Easy testing for devs
=> Setup trpc-panel

.github/renovate.json
Enables Renovate to automerge dependency upgrades.
Completes CFD-18
=> Automerge for Renovate

.github/renovate.json
Prevents Renovate from automerging any major package changes
Let's make sure that our repo stays safe!
=> Enable Automerge for Minor Releases

netlify.toml
Provides an ignore command for Netlify to use
Contributes to CFD-19
Saves build minutes for Netlify.
=> Setup Netlify Ignore

apps/nextjs/src/components/developers/helenaglowacki.tsx, apps/nextjs/src/pages/index.tsx, packages/api/src/router/developer.ts
-  `helenaglowacki_info` : returns info about me!
- `helenaglowacki_upvote` : increments upvote by 1
Completes CFD-11
Don't worry about it
=> [CFD-11] Starter task 2 - Helena

package.json, pnpm-lock.yaml
Removes `@turbo/gen` from root `package.json`
We aren't using generators for this project.
=> Remove @turbo/gen package

apps/expo/package.json
Adds a lint using `expo-doctor` that checks that the Expo project dependencies are the correct versions.
Make sure that Renovate doesn't break our Expo app.
=> Add lint for Expo package versions

packages/db/prisma/migrations/20231028182422_add_absence_model/migration.sql, packages/db/prisma/schema.prisma
Created an Absence Model to track user absences:
Completes CFD-36
Contributes to CFD-27
(I realized I copied the wrong branch name for this ticket orz)
N/A
=> [CFD-36] Create Absence Model

.github/renovate.json, packages/db/prisma/migrations/20231028203404_add_activity_model/migration.sql, packages/db/prisma/schema.prisma
Created an Activity Model in `schema.prisma` with:
(I have not migrated it yet as it says to only do it once per PR, so I will wait for approval first)
Completes CFD-32
Contributes to CFD-28
The video shows changing the time on the `day` time stamp and it reverting as it is not needed. Same goes for `startTime` and `endTime`. 
https://github.com/uoftblueprint/centre-for-dreams/assets/113125436/5b862043-103d-4b21-9545-ab639f424e5a
=> [CFD-32] Add Activity Model

packages/api/src/root.ts, packages/api/src/router/absence.ts, packages/db/prisma/migrations/20231029025802_remove_id_from_absence_model/migration.sql, packages/db/prisma/migrations/20231029035436_new_absence_model/migration.sql, packages/db/prisma/schema.prisma
Created a new tRPC router with endpoints for Absence.
Completes CFD-37
Contributes to CFD-27
=> [CFD-37] Create Absence CRUD Endpoints

.github/workflows/ci.yml
Adds `NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY` to CI environment
Get Ryan's build working
=> Add next publishable key to CI environment

packages/db/prisma/migrations/20231029194452_create_user_model/migration.sql, packages/db/prisma/schema.prisma
Creates a basic user table with only an ID
Needed for PRs that need users for relations.
=> Create user table

.github/workflows/ci.yml, .npmrc, apps/expo/app.config.ts, apps/expo/package.json, apps/nextjs/package.json, pnpm-lock.yaml, tooling/tailwind/package.json
Creates CI checks for iOS and Android builds to ensure that our React Native app can be built at all times. iOS and Android builds are created after all other checks have passed and are not run unless there is a change inside of `apps/expo`
The new checks run on this PR!
=> Create CI Checks for iOS and Android Builds

apps/nextjs/package.json, pnpm-lock.yaml
There is some weird stuff happening with Clerk and Next, pinning it to this version fixes the issue.
Clerk and Netlify issues.
=> Pin nextjs version to 13.4.12

.github/workflows/ci.yml
Fixes typo for Android CI build that prevents the build from running.
CI should work
=> Fix typo in Andoid CI 

.env.example, README.md, apps/nextjs/package.json, apps/nextjs/src/env.mjs, apps/nextjs/src/middleware.ts, apps/nextjs/src/pages/_app.tsx, apps/nextjs/src/pages/index.tsx, packages/api/package.json, packages/api/src/trpc.ts, pnpm-lock.yaml
Completes CFD-41
This PR adds Clerk's authorization middleware for all pages (excluding "/"), and also enforces it for protected routes in tRPC.
You will not be able to see the introduction details of any developer from `developerRouter` unless you're signed in with te sign in button on the bottom of the page.
=> CFD-41: tRPC Auth Middleware

.github/workflows/ci.yml, .github/workflows/expo.yml
Modifies CI configuration to only run Expo builds on merge queue. Also sets up all merge queue CI
Long CI = merge queue more valuable, don't want people to update their PR base all the time
CI checks run for this PR
=> Setup CI for Merge Queue

packages/api/src/root.ts
Fixes tRPC Panel
Broken stuff is bad
Working now
=> Fix tRPC Panel

packages/api/src/router/notification.ts
This PR adds an endpoint to the `notification` router that allows a push token to be associated with a user
Completes CFD-62
None (tRPC panel is broken lol)
=> [CFD-62] Register push token endpoint

packages/api/src/root.ts, packages/api/src/router/announcement.ts, packages/api/src/router/comment.ts, packages/api/src/router/discussion.ts, packages/db/prisma/migrations/20231122201551_add_user_to_post_and_comment/migration.sql, packages/db/prisma/schema.prisma
This PR adds:
- Comment router with CRUD for comments under posts
- A user field to announcement and discussion models for the author of the post
Completes CFD-29
Comment endpoints and modified post models work after basic testing through tRPC panel
=> [CFD-29] Add comment procedures

.github/workflows/cache.yml
Creates a workflow that runs on the `main` branch and caches all dependencies.
Github Actions will only restore caches from the `main` and current branch. Now that we have a merge queue, we aren't caching our dependencies on pushes to main
Hopefully it works
=> Create workflow for pnpm cache

.github/workflows/cache.yml
Fixes error in cache workflow file.
Cache workflow didn't run successfully because OS wasn't specified.
=> Fix Cache Workflow

packages/api/src/router/absence.ts
Updated `absence.ts` to find user by `ctx.userId`. Throws error if user isn't found.
Completes CFD-64
=> [CFD-64] Update Absence Endpoints

pnpm-lock.yaml
Ran `pnpm dedupe`
Why not remove old dependencies 🤷
=> Dedupe pnpm dependencies

apps/expo/src/app/index.tsx, apps/expo/src/components/Comment.tsx
High Fi design for comment component
CFD-82
Completes CFD-82
```const data = {
id: 0,
postId: 0,
text: "Lorem Ipsum",
createdAt: new Date(start),
userId: 1,
}```
for the comment component `<Comment comment={data}></Comment>` in `index.tsx`
=> Sarinali/cfd 82 Update Comment Component

.github/renovate.json
NO MORE RENOVATE
Let our poor devs merge things in without confilcts
=> Run Renovate Monthly

apps/expo/src/components/AnnouncementCard.tsx, apps/expo/src/components/AnnouncementTile.tsx
Updated the announcement card design to use hi-fi designs.
Note that I have left a few placeholders in the code, which will be removed once their is a way to retrieve the corresponding info.
CFD-87
Code for generating test that goes in index.tsx: 
`      <View className="h-full bg-white px-[20px]">
<AnnouncementCard
announcement={{
id: 0,
title: "2023 Markham Santa Claus Parade",
contents: "",
createdAt: new Date(),
postType: "Announcement",
userId: 0,
}}
/>
</View>
`
=> Ram raghav s/cfd 87 update announcement bubble component

apps/expo/app.config.ts, apps/expo/package.json, apps/expo/src/app/_layout.tsx, apps/expo/src/app/index.tsx, apps/expo/src/components/ResetPassword.tsx, apps/expo/src/components/SignInScreen.tsx, apps/expo/src/components/SignInWithOAuth.tsx, apps/expo/src/components/SignOut.tsx, apps/expo/src/components/SignUpScreen.tsx, apps/expo/src/hooks/warmUpBrowser.tsx, pnpm-lock.yaml
Completes CFD-43
Tested by loading into Expo Go
Login page
Toast showing error 
Password reset code
After login
=> CFD-43: Mobile Login/Signup Page

apps/expo/src/components/FilledButtons.tsx
Created Filled and Disabled Button based on the Figma design which also accepts an `onClick` prop that passes a function to the underlying Button.
Completes CFD-78
- Tested the button in `index.tsx`
```
import FilledButton from "~/components/FilledButtons";
function sayHello() {
alert("You clicked me!");
}
```
place in return
```
<FilledButton onClick={sayHello} disabled={true}>
Label
</FilledButton>
<FilledButton onClick={sayHello} disabled={false}>
Label
</FilledButton>
```
=> [CFD-78] Filled Button Components

apps/expo/package.json
Creates a `dev:tunnel` command for Expo
WSL users need to pass the `--tunnel` flag to use Expo Go.
=> Create `dev:tunnel` command for WSL users

apps/expo/src/components/Discussion.tsx
Refactored the Announcement component to a Discussion component. Also changed the props for the component to match the discussion props
CFD-90
=> Refactored announcement component

apps/expo/src/components/Announcement.tsx, apps/expo/src/components/Discussion.tsx
Made design for hi fi in new ticket for announcement
CFD-91
=> Updated design for announcement/discussion

apps/expo/src/components/Discussion.tsx
Added a prop in the discussion component so it is conditionally displayed
CFD-92
Completes CFD-92
=> CFD-92 Edit Prop

.github/renovate.json
Fixes scheduling for dependency updates
Renovate wasn't working because of invalid settings
=> Fix `renovate.json`

.github/workflows/ci.yml
Adds a setup step for Cocoapods for Github Actions
https://github.com/CocoaPods/CocoaPods/issues/12226
=> Set Cocoapods version in Github Actions

apps/expo/src/components/EventTab.tsx
Created a Week Event tab component ✨
Completes CFD-94
1. In `calendar.tsx` add these imports:
```
import type { RouterOutputs } from "~/utils/api";
import EventTab from "~/components/EventTab";
```
2. Create an activity/event: 
```
type GetActivityOutput = RouterOutputs["activity"]["getSchedule"][number];
const myActivityProps: GetActivityOutput= 
{
id: 1,
name: "Event Name",
durationMinutes: 60,
location: "Conference Room",
day: new Date(),
startTime: new Date("2023-10-09T08:00:15.000"),
leader: "me",
};
```
3. Change the view to be the following (_changing background color cause the default is too close to the component color_):
```
<SafeAreaView className="bg-white h-full">
<Stack.Screen options={{ title: "Calendar", headerShown: false }} />
<Text>Calendar</Text>
<View className="w-3/4 …
```
=> [CFD-94] Week Event Tab Component

apps/expo/assets/filter.svg, apps/expo/src/app/notices.tsx, apps/expo/src/components/AnnouncementCard.tsx, packages/api/src/router/announcement.ts
Created the mobile announcements page (in the notices tab) and redesigned the announcement card to hi-fi design.
CFD-95
CFD-88
https://github.com/uoftblueprint/centre-for-dreams/assets/92739966/b1f923cd-8933-44b7-a77e-b6f671e49f2b
=> Announcement page and card 

apps/expo/assets/read.svg, apps/expo/assets/reply.svg, apps/expo/src/components/Announcement.tsx
Added icons for announcement component
CFD-100
=> CFD 100 Added Icons to Announcement

apps/expo/src/app/account.tsx, packages/api/src/router/user.ts
=> CFD-101: create user profile component

apps/expo/src/app/signin.tsx, apps/expo/src/app/signincode.tsx, apps/expo/src/index.d.ts
Creates correct module type for PNG and removes existing typecasts for PNGs.
Blocking #379
=> Create module type for PNG

apps/expo/eas.json
Adds npm and pnpm versions to `eas.json`
Builds were failing on EAS due to differing pnpm versions.
=> Add tooling versons to `eas.json`

apps/expo/src/app/forum.tsx
Updated forum to use a FlatList component
CFD-115
=> CFD 115 Use FlatList in Forum

packages/db/prisma/schema.prisma
Created a database table for likes with relations to `Post` and `User` model.
Completes CFD-116
=> [CFD-116] Create a Likes Model

apps/expo/src/app/forum.tsx
Fix for the ScrollView 
CFD 122
https://github.com/uoftblueprint/centre-for-dreams/assets/74844953/2c8d700a-2e11-4238-9b00-819ae3a80c25
=> CFD 122 Remove Scroll

apps/expo/app.config.ts, apps/expo/src/app/account.tsx, apps/expo/src/app/calendar/index.tsx, apps/expo/src/app/forum.tsx, apps/expo/src/app/notices/index.tsx
=> [CFD-124] Fix background color

apps/expo/package.json, apps/expo/src/app/_layout.tsx, apps/expo/src/utils/api.tsx, apps/expo/src/utils/cache.ts, pnpm-lock.yaml
Includes Clerk token for all tRPC requests. Also uses Expo secure store for storing the token in the application.
Working auth is important!
Ran on Expo Go and received no unauthorized errors from tRPC.
=> Fix Auth for Expo App

apps/expo/src/app/account.tsx
The edit profile button on the account page has been changed and now logs the user out
Edit profile is out of the scope for our functionality and can be added later if needed
Completes CFD-129
=> CFD-129: Change edit profile button to signout

packages/api/src/root.ts, packages/api/src/router/like.ts, packages/db/prisma/migrations/20240316173828_add_likes_model/migration.sql
Created endpoints for liking and unliking posts.
Completes CFD-117
=> [CFD-117] Create Discussion Likes Endpoints

packages/db/prisma/migrations/20240328024225_edit_post_model/migration.sql, packages/db/prisma/schema.prisma
Made title optional for posts in schema
=> [CFD-126] Make title optional in schema

packages/api/src/router/discussion.ts
=> [CFD-127] Remove title from discussion endpoint

apps/expo/src/app/createpost.tsx
Integrated post page with TRPC
Completes CFD-128
https://github.com/uoftblueprint/centre-for-dreams/assets/113125436/624532d4-1a1f-4ab0-a99c-9bff33b738c4
=> [CFD-128] Integrate createpost page with trpc

apps/expo/src/app/account.tsx, packages/api/src/router/user.ts, packages/db/prisma/migrations/20240324200413_add_notification_settings_to_user/migration.sql, packages/db/prisma/schema.prisma
Completes CFD-130
After clicking the toggle buttons, the new states are persisted
=> CFD-130: persist notification settings in database

.vscode/settings.json, README.md
=> Starter Task 1

README.md
=> updated starter task 1

apps/expo/src/app/devcards.tsx, apps/expo/src/components/developers/ElsieZhu.tsx, apps/nextjs/src/components/developers/elsiezhu.tsx, apps/nextjs/src/pages/index.tsx, packages/api/src/router/developer.ts
Added Dev Cards for myself to web and mobile as a part of Starter Task 2. 
Completes CFD-160
=> [CFD-160] Starter Task 2

apps/expo/src/app/devcards.tsx, apps/expo/src/components/developers/Nolawi.tsx, apps/nextjs/src/components/developers/nolawi.tsx, apps/nextjs/src/pages/index.tsx, packages/api/src/router/developer.ts
=> starter task 2

apps/expo/src/app/devcards.tsx, apps/expo/src/components/developers/GirikSetya.tsx, apps/nextjs/src/components/developers/giriksetya.tsx, apps/nextjs/src/pages/index.tsx, packages/api/src/router/developer.ts
=> Task 2 - Girik Setya 

apps/expo/src/components/Discussion.tsx
Linked the post “Comment” button to existing backend endpoint. Comment button now allows adding and displaying comments. This is reflected immediately on the frontend. 
CFD-188
Completes CFD-188
The comments are also added on prisma
=> [CFD-188] Comment Functionality

apps/expo/src/app/editpost.tsx, apps/expo/src/app/forum.tsx, apps/expo/src/components/Discussion.tsx, apps/expo/src/components/NavBar.tsx
Add an “Edit” button on posts within the “My Posts” tab
Should link to the “Edit Post” page, can use similar design to "Create Page" design, just edit text accordingly.
=> edit post page

apps/nextjs/src/components/post.tsx, pnpm-lock.yaml
Can now click anywhere on the post box to open a popup specific to that post instead of clicking the comment icon (built on top off Elsie's PR). Did not implement images because they are not supported yet.
Completes CFD-198
=> CFD-198 post view functionality

apps/expo/src/app/forum.tsx, apps/expo/src/components/Discussion.tsx, packages/api/src/router/discussion.ts
Regress changes to AWS Image display, causing infinite renders.
=> Hotfix Forum Infinite Loop

apps/expo/src/components/Discussion.tsx, apps/expo/src/components/DiscussionPostImage.tsx
Fixes CFD-189
Fixes the infinite loop issue when loading images on Expo.
Completes CFD-
Note: It works on my machine. But please hop on this branch and test again on your machine again before approving it.
=> Expo image loop fix

.github/workflows/ci.yml, apps/nextjs/src/components/absenteestable.tsx, apps/nextjs/src/components/activity/activitycreatemodal.tsx, apps/nextjs/src/components/activity/activityupdatemodal.tsx, apps/nextjs/src/components/eventscalendar.tsx, apps/nextjs/src/components/icons/dropdownicon.tsx, apps/nextjs/src/components/icons/pencilicon.tsx, apps/nextjs/src/components/icons/plusicon.tsx, apps/nextjs/src/components/schedule.tsx, apps/nextjs/src/pages/activities.tsx
Created the Events Calendar for the `/activities` page; allowing a user to view all activities scheduled for a particular day, edit activities, and create new activities. Also extracted some SVGs into icon components.
Completes [CFD-205](https://linear.app/uoftblueprint/issue/CFD-205/event-calendar)
https://github.com/user-attachments/assets/a31814a9-5034-436a-a4b4-61ee48ac3957
=> [CFD-205] Event Calendar
