uoftblueprint/centre-for-dreams

- packages/api/src/root.ts
- packages/api/src/router/post.ts
Adds the `post` router to API and `getPosts` query endpoint.
Completes CFD-21
Given these rows in the database:
`curl http://localhost:3000/api/trpc/post.getPosts` returns
```json
{
"result": {
"data": {
"json": [
{
"id": 3,
"title": "test post",
"contents": "asdf",
"createdAt": "2023-10-19T22:01:55.057Z"
},
{
"id": 2,
"title": "hello world",
"contents": "lorem ipsum",
"createdAt": "2023-10-19T04:59:20.060Z"
},
{
"id": 1,
"title": "first post",
"contents": "hello",
"createdAt": "2023-10-19T04:54:20.060Z"
}
],
"meta": {
"values": {
"0.createdAt": [
"Date"
],
"1.createdAt": [
"Date"
],
"2.createdAt": [
"Date"
]
}
}
}
}
}
```
> Add: post router and getPosts endpoint

- apps/nextjs/package.json
- pnpm-lock.yaml
Keeps the Next.js version under 13.5
Next.js version 13.5 is not yet supported on Netlify: https://answers.netlify.com/t/runtime-importmoduleerror-error-cannot-find-module-styled-jsx-style/102375/14
> Downgrade Next for Netlify Deploy

- netlify.toml
Uses `npx` instead of `pnpm dlx` for the Netlify Ignore command.
Netlify does not have `pnpm` installed when the ignore command is run.
> Fix Netlify Ignore Command

- apps/expo/package.json
- pnpm-lock.yaml
This reverts commit 8ec4b0de29b74d89c2d316934d35f4144d93a2a3.
> Revert "Update dependency react-native-gesture-handler to ~2.13.0 (#43)"

- .github/workflows/ci.yml
- apps/expo/package.json
- pnpm-lock.yaml
Moves `expo-doctor` check from `pnpm lint` to a separate check.
Helps with caching the results of eslint
> Add CI check for Expo packages validity

- .github/renovate.json
Adds `next` to "ignoreDeps" for Renovate
We don't want to update Next until Netlify can support a version above 13.4
> Prevent Nextjs upgrades

- .github/renovate.json
Removes the monorepo grouping setting from Renovate that causes the immortal Expo PR
Expo dependency management is terrible
> Remove group:monorepos setting from Renovate

- .github/renovate.json
Reverts uoftblueprint/centre-for-dreams#53
Adds `group:expoMonorepo` to `ignorePresets`. Pls work 🙏
> Remove expo monorepo preset from recommended config

- .github/renovate.json
Changes range strategy to `bump` instead of `auto`.
Renovate does not support `pnpm` lockfiles, so bump is required to update certain dependencies.
> Renovate bump dependencies

- .github/renovate.json
Adds minimum release age for Renovate, so dependencies won't be updated until the update is 5 days old.
Want to make sure that updates work
> Add Minimum Release Age for Renovate

- .github/workflows/ci.yml
Fixes ignore command so that iOS and Android builds are run on main branch.
Previous command would compare to the main branch (good for PRs), but this means that any commit to main branch will cause the workflow to be ignored.
> Fix ignored mobile builds on main branch

- apps/expo/package.json
Makes Expo Go the default for when `pnpm dev` is used.
Not sure why, but it no longer defaults to expo go
Tested locally and confirmed it works
> Make Expo Go the default for development

- apps/expo/package.json
- pnpm-lock.yaml
Updates the version of `expo-dev-client` package to `~2.4.12`
Our CI is breaking because Expo will not build an app with a package version that was allowed until today (thanks expo)!
Lint CI should pass
> Update expo-dev-client to ~2.4.12

- apps/nextjs/package.json
- apps/nextjs/src/utils/api.ts
- pnpm-lock.yaml
Removes `@cfd/logger` as a dependency of the Next.js app.
The logger was included for logging requests, but this should only be done on the server side, not on the client side. This also slightly reduces the bundle size of the web app.
> Remove Client Logger Dependency

- packages/api/src/router/post.ts
- packages/db/prisma/migrations/20231105001203_add_post_type/migration.sql
- packages/db/prisma/schema.prisma
Adds a PostType enum (currently with two options: announcement and discussion) and adds a postType field to posts
Completes CFD-55
New field and endpoint changes works as expected in Prisma Studio and tRPC panel
> [CFD-55] Add postType to post model

- packages/db/index.ts
- packages/db/package.json
- packages/db/prisma/schema.prisma
- pnpm-lock.yaml
Changed Prisma driver from the default Postgres driver to the Neon Serverless driver
Making DB connections is slow, contributing to poor cold starts on our Netlify deployment. The Neon driver uses HTTP requests instead of a DB connection, improving the performance of our DB queries
I got the following results on my local machine, and repeated the experiments to ensure that results are consistent.
Default driver (before):
Serverless driver (after): 
Default driver (before): 
Serverless driver (after):
> Use Neon Serverless Driver with Prisma

- packages/api/src/root.ts
- packages/api/src/router/developer.ts
- packages/api/src/router/user.ts
- packages/api/src/trpc.ts
- packages/db/prisma/migrations/20231111232813_add_clerk_id_to_user_table/migration.sql
- packages/db/prisma/schema.prisma
Completes CFD-61
- Add clerkId to the users table, a unique field mapping users in our database to their clerkId
- When users are returned in the auth state, we also return their id within OUR database, which is a monotonically increasing integer
- If the user isn't present in the database, we insert them in there with their clerkId
Updated upvote for Ryan Li card on the home page to use protected procedure, which should create the corresponding user in the database if it did not exist before when the button is used.
> [CFD-61] Endpoints to query users in our database

- apps/expo/src/components/inputs/TextInput.tsx
- apps/expo/src/components/inputs/index.ts
Adds a flexible and customizable text input component based on React Native's `TextInput`
Completes CFD-79
Tested single-line input, multiline input, different input modes (email, numeric, password, etc.).
Example code:
```typescript
import Ionicons from "@expo/vector-icons/Ionicons";
import { TextInput } from "~/components/inputs";
<TextInput
placeholder="Write description here..."
multiline
className="my-2 h-[168px]"
/>
<View>
<TextInput placeholder="Search" inputMode="numeric" multiline>
<TextInput.RightElement>
<Ionicons
name="search"
size={24}
color="black"
onPress={() => alert("hi there")}
/>
</TextInput.RightElement>
</TextInput>
</View>
<TextInput
placeholder="Enter email"
multiline
className="my-2"
inputMode="email"
/>
```
> [CFD-79] Create input box components

- apps/expo/src/components/NavBar.tsx
Fixed navbar sizing to work with different screen sizes.
_Note:_ I made the tab bar label inside the tab bar icon slot, instead of on its own. It is much easier to align everything and move everything together that way. Otherwise there was some weird sizing things. But I can change it back if you want.
Completes CFD-119
I tried to minimize the space at the bottom as much as i could...
> [CFD-119] Fixed nav bar sizing

- packages/api/src/trpc.ts
This PR fixes the issue where paticipant IDs will be re-used when logging in with another account since it was hard coded to `1`. This PR will change to create a new unique participant object without hard coding the ID and linking it to the user.
`protectedProcedure` was unable to be used since it inserted the user into the database if they didn't exist on each run. This means that if the user logged in with a different account the insertion would fail because the participant id would clash.
Fixes CFD-63
Completes CFD-133
Source: trust me bro
> CFD-133: Fix auth middleware participant unique key constraint

- apps/expo/src/utils/api.tsx
Invalidates query cache whenever a mutation is made.
This is the behavior currently used for the Nextjs client, but was not added to the Expo app.
> Invalidate Expo Query Cache on Mutation

- apps/expo/src/app/calendar/index.tsx
- Fetch activities from the api and displays them on the mobile app in ascending order
- converts 24 to 12 hour format and displays them in ascending order
- loading animation while the activities are being fetched from the api
- scrolling feature 
- displays "No activities" if there are no activities for a week/day
https://linear.app/uoftblueprint/issue/CFD-152/display-activity-on-mobile-from-database
Completes CFD- 152
1. (Skip this step if you are signed in) change every "protectedProcedure" to "publicProcedure" in activity.ts
2. add the following test data in http://localhost:5556/
3. on the expo app, you should see the following (currently fetching the activities within 7 days of today (nov 11) and results may vary depending on when you run this):
> [CFD 152] display activity on mobile from database

- apps/expo/package.json
- apps/nextjs/src/components/navbar.tsx
- apps/nextjs/src/pages/inviteuser.tsx
- apps/nextjs/src/pages/posts.tsx
- pnpm-lock.yaml
Implemented Invite User page according to the Figma design. Note that this page is not connected to the backend yet
Completes [CFD-194](https://linear.app/uoftblueprint/issue/CFD-194/invite-new-user-page)
> [CFD-194] Invite New User Page
